### ISSUE TITLE
add password auth option back

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/sda-uploader#27]
it was removed at some point, but FEGA needs it
added https://github.com/CSCfi/sda-uploader/commit/f1384c11f8bba8df5db4d9dba24de17f557a3421
removed https://github.com/CSCfi/sda-uploader/commit/927f14f5cf68829c47d8c20085fd958c4d6cbc38

**Comment by blankdots** [comment]
I remember we removed it because it was confusing, and not necessary.
should we attempt a redesign if this is going to be used more than it was initially intended for ? 
cc @ainoc
